export default {
    "Anhui": "Anhui",
    "Beijing": "Beijing",
    "Chongqing": "Chongqing",
    "Fujian": "Fujian",
    "Guangdong": "Guangdong",
    "Gansu": "Gansu",
    "Guangxi": "Guangxi Zhuang",
    "Guizhou": "Guizhou",
    "Hainan": "Hainan",
    "Hebei": "Hebei",
    "Henan": "Henan",
    "Hong Kong": "Hong Kong",
    "Heilongjiang": "Heilongjiang",
    "Hunan": "Hunan",
    "Hubei": "Hubei",
    "Jilin": "Jilin",
    "Jiangsu": "Jiangsu",
    "Jiangxi": "Jiangxi",
    "Liaoning": "Liaoning",
    "Macau": "Macau",
    "Inner Mongolia": "Nei Mongol",
    "Ningxia": "Ningxia Hui",
    "Qinghai": "Quinghai",
    "Shaanxi": "Shaanxi",
    "Sichuan": "Sichuan",
    "Shandong": "Shandong",
    "Shanghai": "Shanghai",
    "Shanxi": "Shanxi",
    "Tianjin": "Tianjin",
    "Taiwan": "Taiwan",
    "Xinjiang": "Xinjiang Uygur",
    "Tibet Autonomous Region": "Xizang (Tibet) ",
    "Yunnan": "Yunnan",
    "Zhejiang": "Zhejiang"
}